FROM golang:1.20-alpine AS build
WORKDIR /app
COPY server/ .
RUN go build -o /pubsub-server ./main.go

FROM alpine:3.18
RUN apk add --no-cache ca-certificates
COPY --from=build /pubsub-server /pubsub-server
EXPOSE 8080
CMD ["/pubsub-server"]
