FROM golang:1.20-alpine AS build
WORKDIR /app
COPY client/ .
RUN go build -o /pubsub-client ./main.go

FROM alpine:3.18
RUN apk add --no-cache ca-certificates
COPY --from=build /pubsub-client /pubsub-client
CMD ["/pubsub-client"]
