version: '3.8'

services:
  # Três instâncias independentes do Broker
  broker1:
    image: eclipse-mosquitto:latest
    hostname: broker1
    volumes:
      - ./mosquitto/config:/mosquitto/config
    ports:
      - "1883:1883" # Broker principal

  broker2:
    image: eclipse-mosquitto:latest
    hostname: broker2
    volumes:
      - ./mosquitto/config:/mosquitto/config
    ports:
      - "1884:1883" # Broker de backup 1

  broker3:
    image: eclipse-mosquitto:latest
    hostname: broker3
    volumes:
      - ./mosquitto/config:/mosquitto/config
    ports:
      - "1885:1883" # Broker de backup 2

  server:
    build: .
    container_name: game-server
    ports:
      - "8080:8080"
    depends_on:
      - broker1
      - broker2
      - broker3
    volumes:
      - ./data:/app/data